name: Build and Sync to Glitch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Week 3 - Intro to React
        run: |
          cd ./classes/week-3/intro-to-react
          npm install
          npm run build
      - name: Sync week 3 - Intro to React
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: "${{ secrets.glitchAuthToken }}"
          project-id: "${{ secrets.week3ProjectId }}"
          path: "classes/week-3/intro-to-react/dist"
