name: Build and Sync to Glitch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Week 3 - Intro to React
        run: |
          cd ./classes/week-3/intro-to-react
          npm ci
          npm run build
      - name: Week 3 - Intro to React three fiber
        run: | # Week 3 - Intro to React three fiber
          cd ./classes/week-3/intro-to-r3f
          npm ci
          npm run build

  # Minimal test of the GitHub Action
  # (only runs on pushes to the `main` branch)
  # Glitch Project: https://glitch.com/edit/#!/github-action
  # sync:
  #   if: github.event.ref == 'refs/heads/main' # Only main branch deploys to Glitch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Sync week 3 - Intro to React
  #       uses: kanadgupta/glitch-sync@main
  #       with:
  #         auth-token: "${{ secrets.glitchAuthToken }}"
  #         project-id: "${{ secrets.week3ProjectId }}"
