name: Build and Sync to Glitch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Week 3 - Intro to React
        run: |
          cd ./classes/week-3/intro-to-react
          npm install
          npm run build
      - name: Build Week 3 - Intro to React three fiber
        run: |
          cd ./classes/week-3/intro-to-r3f
          npm install
          npm run build
      - name: Build Week 5 - Scene Graph
        run: |
          cd ./classes/week-5/scene-graph-r3f
          npm install
          npm run build
      - name: Build Week 5 - Visual Explainers
        run: |
          cd ./classes/week-5/visual-explainers-r3f
          npm install
          npm run build
      - name: Build Week 8 - Materials
        run: |
          cd ./classes/week-8/materials-r3f
          npm install
          npm run build
      - name: Build Week 8 - Animated Highlights
        run: |
          cd ./classes/week-8/animated-highlights-r3f
          npm install
          npm run build
      - name: Build Week 10 - Data, Controls, Interactions
        run: |
          cd ./classes/week-10/data-controls-interactions-r3f
          npm install
          npm run build
      - name: Build Week 13 - File Animations
        run: |
          cd ./classes/week-13/file-animations-r3f
          npm install
          npm run build
      - name: Build Week 13 - Post Processing
        run: |
          cd ./classes/week-13/post-processing-r3f
          npm install
          npm run build
  # Minimal test of the GitHub Action
  # (only runs on pushes to the `main` branch)
  # Glitch Project: https://glitch.com/edit/#!/github-action
  # sync:
  #   if: github.event.ref == 'refs/heads/main' # Only main branch deploys to Glitch
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Sync week 3 - Intro to React
  #       uses: kanadgupta/glitch-sync@main
  #       with:
  #         auth-token: "${{ secrets.glitchAuthToken }}"
  #         project-id: "${{ secrets.week3ProjectId }}"
  #         path: 'classes/week-3/intro-to-react/dist'
